### ISSUE TITLE
(Pre-release testing) 0.14 regression bug - switching from BEX compare to Java compare results in exception

### ISSUE THREAD

**Issue by CodesAway** [CodesAway/BEXCodeCompare#117]
Need to fix bug when switch from BEX compare to Java compare
(seems like it's doing a compare even though I'm exiting from BEX compare)
(either short circuit this or at east prevent an error)
(ideally, it shouldn't be doing a compare when switch away from BEX compare)

**This MUST be fixed before 0.14 can be released**

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at info.codesaway.bex.parsing.BEXString.substring(BEXString.java:93)
	at info.codesaway.bex.parsing.BEXString.substring(BEXString.java:89)
	at info.codesaway.bex.compare.RangeComparatorBEX.normalizeLine(RangeComparatorBEX.java:410)
	at info.codesaway.bex.compare.RangeComparatorBEX.lambda$3(RangeComparatorBEX.java:125)
	at info.codesaway.bex.BEXPair.map(BEXPair.java:56)
	at info.codesaway.bex.compare.RangeComparatorBEX.lambda$2(RangeComparatorBEX.java:125)
	at info.codesaway.bex.diff.BEXNormalizationFunction.normalize(BEXNormalizationFunction.java:37)
	at info.codesaway.bex.compare.RangeComparatorBEX.computeDifferences(RangeComparatorBEX.java:251)
	at info.codesaway.bex.compare.RangeComparatorBEX.findDifferences(RangeComparatorBEX.java:80)
	at info.codesaway.eclipse.compare.rangedifferencer.RangeDifferencer.findDifferences(RangeDifferencer.java:114)
	at info.codesaway.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:327)
	at info.codesaway.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:411)
	at info.codesaway.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:389)
	at info.codesaway.eclipse.compare.internal.merge.DocumentMerger.lambda$0(DocumentMerger.java:471)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by CodesAway** [comment]
Bug fixed. Learned that when switching from BEX compare to Java compare, it still calls BEX compare with an empty file for both left / right, which was causing the error.

I added short-circuit logic that if both text is empty, no compare is needed.

No clue why Eclipse calls BEX compare when trying to close BEX compare to Java compare (seems like a bug on their part). However, I worked around it.
